/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['.directed-graph {\n  user-select: none; }\n  .directed-graph .edge {\n    stroke: #666;\n    fill: none; }\n    .directed-graph .edge .edge-label {\n      stroke: none;\n      font-size: 12px;\n      fill: #ffffff; }\n  .directed-graph .panning-rect {\n    fill: transparent;\n    cursor: move; }\n  .directed-graph .node-group .node:focus {\n    outline: none; }\n'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1ZvbHVtZXMvYWxpZW4vZm9ya2VkL25neC1jaGFydHMtZGFnL2J1aWxkL2RpcmVjdGVkLWdyYXBoL2RpcmVjdGVkLWdyYXBoLmNvbXBvbmVudC5jc3MubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1ZvbHVtZXMvYWxpZW4vZm9ya2VkL25neC1jaGFydHMtZGFnL2J1aWxkL2RpcmVjdGVkLWdyYXBoL2RpcmVjdGVkLWdyYXBoLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
